### ISSUE TITLE
Home assistant 

### ISSUE THREAD

**Issue by vednolacni** [zejn/arsoapi#10]
Živjo ma kdo kej od tega uvoženo v home assistant?

**Comment by zejn** [comment]
Za dež in verjetnost toče lahko uporabiš rest plugin. Tole dodaš v configuration.yaml:

```
rest:
  - resource_template: "https://opendata.si/vreme/report/?lat={{ '{:.2f}'.format(state_attr('zone.home', 'latitude')) }}&lon={{ '{:.2f}'.format(state_attr('zone.home', 'longitude')) }}"
    scan_interval: 180
    sensor:
      - name: "ARSO Dež"
        json_attributes_path: "$.radar"
        value_template: "{{ value_json['radar']['rain_mmph'] }}"
        unit_of_measurement: "mm/h"
        json_attributes:
          - "rain_level"
          - "rain_mmph"
      - name: "ARSO Verjetnost toče"
        json_attributes_path: "$.hailprob"
        value_template: "{{ value_json['hailprob']['hail_level'] }}"
        unit_of_measurement: "%"
        json_attributes:
          - "hail_level"

```
